"""Adding Requested Appointments and renaming a table

Revision ID: 669cd87a1958
Revises: 
Create Date: 2023-11-26 10:28:25.687065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '669cd87a1958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_email_address', sa.String(length=200), nullable=False),
    sa.Column('email_date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requested_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('service_requested', sa.String(length=20), nullable=False),
    sa.Column('date_requested', sa.Date(), nullable=False),
    sa.Column('customer_message', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.drop_table('requested_appointments')
    op.drop_table('email_subscribers')
    # ### end Alembic commands ###
